
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Damage = _buf.ReadInt();
        Prefab = _buf.ReadString();
    }

    public static Bullet DeserializeBullet(ByteBuf _buf)
    {
        return new Bullet(_buf);
    }

    public readonly int Id;
    public readonly int Damage;
    public readonly string Prefab;
   
    public const int __ID__ = 2000900386;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "damage:" + Damage + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}
