
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public demo.TbTurret TbTurret {get; }
    public demo.TbBullet TbBullet {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbTurret = new demo.TbTurret(loader("demo_tbturret"));
        TbBullet = new demo.TbBullet(loader("demo_tbbullet"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbTurret.ResolveRef(this);
        TbBullet.ResolveRef(this);
    }
}

}
