
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Turret : Luban.BeanBase
{
    public Turret(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BulletId = _buf.ReadInt();
        FireRate = _buf.ReadFloat();
        Prefab = _buf.ReadString();
    }

    public static Turret DeserializeTurret(ByteBuf _buf)
    {
        return new Turret(_buf);
    }

    public readonly int Id;
    public readonly int BulletId;
    public readonly float FireRate;
    public readonly string Prefab;
   
    public const int __ID__ = -1778557680;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bulletId:" + BulletId + ","
        + "fireRate:" + FireRate + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}
